export type AIProposal={values:Record<string,unknown>|null;provider:string;model:string;prompt_version:string;rule_version:string;finished_at:string|null};
export type EventItem={id:string;title_ja:string;summary_ja:string;event_date:string;date_certainty:string;category:string;relevance_status:string;relevance_reason:string|null;importance_level:string|null;importance_score:number|null;importance_reason:string|null;must_include:boolean;must_include_reason:string|null;certainty:string;publication_status:string;version:number;rule_version:string;prompt_version:string;created_at?:string;updated_at?:string;articles?:Article[];revisions?:Revision[];ai_proposal?:AIProposal|null};
export type Article={id:string;title:string;url:string;published_at:string|null;publisher:string;feed_id:string;is_primary_source:boolean;link_reason:string};
export type Revision={id:string;version:number;reason:string|null;created_at:string};
export type CalendarDay={date:string;count:number;highest_importance:string|null;has_must_include:boolean;categories:string[]};
export type EventPage={items:EventItem[];total:number;offset:number;limit:number;has_more:boolean};
export type Candidate={id:string;event_id:string;candidate_event_id:string;similarity_score:number;reasons:string[];status:string};
export type Feed={id:string;name:string;url:string;publisher:string;declared_language:string|null;default_category:string|null;trust_score:number|null;enabled:boolean;fetch_interval_minutes:number;last_success_at:string|null;last_failure_at:string|null;consecutive_failures:number;updated_at:string;version:number};
export type Job={id:string;job_type:string;status:string;attempts:number;max_attempts:number;created_at:string;run_after:string;last_error_code:string|null};
export type FetchRun={id:string;status:string;http_status:number|null;fetched_count:number;inserted_count:number;started_at:string;finished_at:string|null;error_code:string|null};
export type SimilarExamples={dataset_version:string;dataset_sha256:string;rubric_version:string;matches:Array<{id:string;scenario:string;expected_relevance:string;expected_importance:string|null;must_include:boolean;reason:string;tags:string[];similarity:number}>};
export class ApiError extends Error{constructor(public status:number,message:string){super(status===409?`${message} 最新内容を再読み込みして確認してください。`:message)}}
let csrf='';
export function csrfForTest(){return csrf}
async function request<T>(path:string,init:RequestInit={},signal?:AbortSignal):Promise<T>{
  const headers=new Headers(init.headers);if(init.body)headers.set('Content-Type','application/json');if(!['GET','HEAD'].includes(init.method||'GET')&&csrf)headers.set('X-CSRF-Token',csrf);
  const response=await fetch(`/api/v1${path}`,{...init,headers,credentials:'same-origin',signal});if(!response.ok){let message=`HTTP ${response.status}`;try{message=(await response.json()).message||message}catch{}throw new ApiError(response.status,message)}
  return response.status===204?undefined as T:response.json();
}
export const api={
  async login(username:string,password:string){const value=await request<{csrf_token:string}>('/auth/login',{method:'POST',body:JSON.stringify({username,password})});csrf=value.csrf_token},
  async me(signal?:AbortSignal){const value=await request<{username:string;csrf_token:string}>('/auth/me',{},signal);csrf=value.csrf_token;return value},
  logout:()=>request<void>('/auth/logout',{method:'POST'}),calendar:(month:string,include=false,signal?:AbortSignal)=>request<{month:string;days:CalendarDay[]}>(`/calendar?month=${encodeURIComponent(month)}&include_drafts=${include}`,{},signal),
  events:(params:URLSearchParams,signal?:AbortSignal)=>request<EventPage>(`/events?${params}`,{},signal),event:(id:string,signal?:AbortSignal)=>request<EventItem>(`/events/${encodeURIComponent(id)}`,{},signal),
  patch:(id:string,body:object)=>request<EventItem>(`/events/${id}`,{method:'PATCH',body:JSON.stringify(body)}),review:(id:string,body:object)=>request<{event:EventItem}>(`/events/${id}/review`,{method:'POST',body:JSON.stringify(body)}),
  merge:(id:string,body:object)=>request<EventItem>(`/events/${id}/merge`,{method:'POST',body:JSON.stringify(body)}),split:(id:string,body:object)=>request<EventItem>(`/events/${id}/split`,{method:'POST',body:JSON.stringify(body)}),cluster:(id:string)=>request<{job_id:string}>(`/events/${id}/cluster`,{method:'POST'}),
  candidates:(id:string,signal?:AbortSignal)=>request<Candidate[]>(`/events/${id}/cluster-candidates`,{},signal),decideCandidate:(eventId:string,id:string,status:string,reason:string)=>request<{status:string}>(`/events/${eventId}/cluster-candidates/${id}`,{method:'PATCH',body:JSON.stringify({status,reason})}),
  feeds:(signal?:AbortSignal)=>request<Feed[]>('/feeds',{},signal),createFeed:(body:object)=>request<Feed>('/feeds',{method:'POST',body:JSON.stringify(body)}),testFeedUrl:(url:string)=>request<{reachable:boolean;accepted_entries:number}>('/feeds/test-url',{method:'POST',body:JSON.stringify({url})}),patchFeed:(id:string,body:object)=>request<Feed>(`/feeds/${id}`,{method:'PATCH',body:JSON.stringify(body)}),testFeed:(id:string)=>request<{reachable:boolean;accepted_entries:number}>(`/feeds/${id}/test`,{method:'POST'}),jobs:(signal?:AbortSignal)=>request<Job[]>('/jobs?limit=30',{},signal),retryJob:(id:string)=>request<{job_id:string}>(`/jobs/${id}/retry`,{method:'POST'}),runs:(signal?:AbortSignal)=>request<FetchRun[]>('/fetch-runs?limit=30',{},signal),fetchFeed:(id:string)=>request<{job_id:string}>(`/feeds/${id}/fetch`,{method:'POST'}),
  providers:(signal?:AbortSignal)=>request<{selected:string;providers:Array<{provider:string;enabled:boolean;healthy:boolean;model:string;detail:string}>}>('/ai/providers',{},signal),testProvider:(name:string)=>request<{schema_valid:boolean}>(`/ai/providers/${name}/test`,{method:'POST'}),evalImportance:(signal?:AbortSignal)=>request<Record<string,unknown>>('/evals/importance',{},signal),runEval:()=>request<{job_id:string}>('/evals/importance/run',{method:'POST'}),reanalyze:(id:string)=>request<{job_id:string}>(`/events/${id}/reanalyze`,{method:'POST'}),similarExamples:(id:string,signal?:AbortSignal)=>request<SimilarExamples>(`/events/${id}/similar-examples?limit=5`,{},signal)
};
