import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import axe from 'axe-core';
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
const emptyPage={items:[],total:0,offset:0,limit:50,has_more:false};
async function boot(handler:(url:string,init?:RequestInit)=>Promise<Response>){vi.resetModules();document.documentElement.lang='ja';document.title='Vietnam Journal';document.body.innerHTML='<a class="skip" href="#main">本文へ</a><div id="app"></div>';vi.stubGlobal('fetch',vi.fn((input:string|URL|Request,init?:RequestInit)=>handler(String(input),init)));await import('./main');await vi.waitFor(()=>expect(document.querySelector('main')).not.toBeNull())}
async function expectAccessible(){const result=await axe.run(document,{rules:{'color-contrast':{enabled:false}}});expect(result.violations.map(item=>item.id)).toEqual([])}
describe('UI accessibility and routing',()=>{beforeEach(()=>history.replaceState({},'', '/'));afterEach(()=>vi.unstubAllGlobals());
  it('renders an accessible login with no inline handlers',async()=>{await boot(async()=>response({message:'authentication required'},401));expect(document.querySelector('form#login')).not.toBeNull();expect(document.querySelectorAll('[onclick]').length).toBe(0);expect(document.querySelector('[role="alert"]')).not.toBeNull();await expectAccessible()});
  it('shows login failures in the dedicated alert',async()=>{await boot(async()=>response({message:'authentication required'},401));const form=document.querySelector<HTMLFormElement>('#login')!,inputs=form.querySelectorAll<HTMLInputElement>('input');inputs[0].value='admin';inputs[1].value='bad-password';form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await vi.waitFor(()=>expect(document.querySelector('#login-error')?.textContent).toContain('authentication required'))});
  it('renders a semantic calendar and supports arrow navigation',async()=>{await boot(async url=>url.endsWith('/auth/me')?response({username:'admin',csrf_token:'x'}):url.includes('/calendar?')?response({month:'2026-07',days:[]}):response(emptyPage));await vi.waitFor(()=>expect(document.querySelector('table.calendar')).not.toBeNull());const buttons=[...document.querySelectorAll<HTMLButtonElement>('.calendar [data-date]')];buttons[0].focus();buttons[0].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));expect(document.activeElement).toBe(buttons[1]);expect(document.querySelectorAll('th[scope="col"]').length).toBe(7);expect(document.querySelectorAll('[onclick]').length).toBe(0);await expectAccessible()});
  it('restores a calendar-view event deep link',async()=>{history.replaceState({},'','/?view=calendar&month=2026-07&event=e1');const event={id:'e1',title_ja:'安全な題名',summary_ja:'要約',event_date:'2026-07-01',date_certainty:'confirmed',category:'economy',relevance_status:'target',relevance_reason:'理由',importance_level:'high',importance_score:90,importance_reason:'根拠',must_include:false,must_include_reason:null,certainty:'confirmed',publication_status:'needs_review',version:1,rule_version:'v1',prompt_version:'v1',articles:[],revisions:[]};await boot(async url=>url.endsWith('/auth/me')?response({username:'admin',csrf_token:'x'}):url.includes('cluster-candidates')?response([]):url.includes('similar-examples')?response({dataset_version:'importance-v1',dataset_sha256:'a'.repeat(64),rubric_version:'v1',matches:[]}):response(event));await vi.waitFor(()=>expect(document.querySelector('.detail h2')?.textContent).toBe('安全な題名'))});
  it('renders paginated review count and CSP-compatible fatal retry',async()=>{history.replaceState({},'','/?view=review&month=2026-07');await boot(async url=>url.endsWith('/auth/me')?response({username:'admin',csrf_token:'x'}):response({...emptyPage,total:51,has_more:true}));await vi.waitFor(()=>expect(document.querySelector('#load-more')).not.toBeNull());expect(document.querySelectorAll('[onclick]').length).toBe(0);await expectAccessible()})
  it('applies category after calendar to review navigation and handles popstate',async()=>{history.replaceState({},'','/?view=calendar&month=2026-07&category=economy');const calls:string[]=[];await boot(async url=>{calls.push(url);return url.endsWith('/auth/me')?response({username:'admin',csrf_token:'x'}):url.includes('/calendar?')?response({month:'2026-07',days:[]}):response(emptyPage)});document.querySelector<HTMLButtonElement>('[data-view="review"]')!.click();await vi.waitFor(()=>expect(calls.some(url=>url.includes('status=needs_review')&&url.includes('category=economy'))).toBe(true));history.pushState({},'','/?view=calendar&month=2026-08&date=2026-08-01');dispatchEvent(new PopStateEvent('popstate'));await vi.waitFor(()=>expect(document.querySelector('h2')?.textContent).toContain('2026年 8月'))})
  it('loads every selected-day page beyond 100 items',async()=>{const calls:string[]=[];await boot(async url=>{calls.push(url);if(url.endsWith('/auth/me'))return response({username:'admin',csrf_token:'x'});if(url.includes('/calendar?'))return response({month:'2026-07',days:[]});return response({...emptyPage,total:101,limit:100,has_more:url.includes('offset=0')})});await vi.waitFor(()=>expect(document.querySelector('#load-more')).not.toBeNull());document.querySelector<HTMLButtonElement>('#load-more')!.click();await vi.waitFor(()=>expect(calls.some(url=>url.includes('offset=100'))).toBe(true))})
  it('clears range filters when a date is selected',async()=>{history.replaceState({},'','/?month=2026-07&from=2026-07-01&to=2026-07-31');await boot(async url=>url.endsWith('/auth/me')?response({username:'admin',csrf_token:'x'}):url.includes('/calendar?')?response({month:'2026-07',days:[]}):response(emptyPage));await vi.waitFor(()=>expect(document.querySelector('.calendar [data-date]')).not.toBeNull());document.querySelector<HTMLButtonElement>('.calendar [data-date]')!.click();expect(location.search).not.toContain('from=');expect(location.search).not.toContain('to=')})
  it('recovers safely from malformed device-local hidden jobs',async()=>{localStorage.setItem('hiddenJobs','{broken');await boot(async url=>url.endsWith('/auth/me')?response({username:'admin',csrf_token:'x'}):url.includes('/calendar?')?response({month:'2026-07',days:[]}):response(emptyPage));const {readHiddenJobs}=await import('./main');expect([...readHiddenJobs()]).toEqual([])})
  it('maps an empty importance score to null and enforces its range',async()=>{await boot(async()=>response({message:'authentication required'},401));const {optionalImportanceScore}=await import('./main');expect(optionalImportanceScore('')).toBeNull();expect(optionalImportanceScore('100')).toBe(100);expect(()=>optionalImportanceScore('101')).toThrow(/0〜100/)})
  it('uses an assertive alert for mutation errors and restores polite status for success',async()=>{await boot(async()=>response({message:'authentication required'},401));document.body.insertAdjacentHTML('beforeend','<div id="toast" role="status" aria-live="polite"></div>');const {toast}=await import('./main');toast('失敗',true);const node=document.querySelector('#toast')!;expect(node.getAttribute('role')).toBe('alert');expect(node.getAttribute('aria-live')).toBe('assertive');toast('成功');expect(node.getAttribute('role')).toBe('status');expect(node.getAttribute('aria-live')).toBe('polite')})
  it('binds fatal retry without inline JavaScript',async()=>{await boot(async url=>url.endsWith('/auth/me')?response({username:'admin',csrf_token:'x'}):response({message:'temporary failure'},500));await vi.waitFor(()=>expect(document.querySelector('#retry')).not.toBeNull());expect(document.querySelector('#retry')?.hasAttribute('onclick')).toBe(false)})
});
