"""initial_schema_phase1

Revision ID: 57ef74b846aa
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
revision: str = '57ef74b846aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_ja', sa.Text(), nullable=False),
    sa.Column('summary_ja', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('date_certainty', sa.Enum('confirmed', 'estimated', 'published_fallback', name='date_certainty'), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('relevance_status', sa.Enum('target', 'out_of_scope', 'uncertain', name='relevance_status'), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.Enum('low', 'middle', 'middle_high', 'high', name='importance_level'), nullable=True),
    sa.Column('importance_score', sa.SmallInteger(), nullable=True),
    sa.Column('importance_reason', sa.Text(), nullable=True),
    sa.Column('must_include', sa.Boolean(), nullable=False),
    sa.Column('must_include_reason', sa.Text(), nullable=True),
    sa.Column('certainty', sa.Enum('confirmed', 'partially_confirmed', 'planned', 'speculative', name='event_certainty'), nullable=False),
    sa.Column('publication_status', sa.Enum('draft', 'needs_review', 'approved', 'hidden', name='publication_status'), nullable=False),
    sa.Column('current_revision_id', sa.UUID(), nullable=True),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('importance_score IS NULL OR importance_score BETWEEN 0 AND 100', name='ck_events_importance_score'),
    sa.CheckConstraint('NOT must_include OR (must_include_reason IS NOT NULL AND length(trim(must_include_reason)) > 0)', name='ck_events_must_reason'),
    sa.CheckConstraint("relevance_status <> 'out_of_scope' OR (importance_level IS NULL AND importance_score IS NULL)", name='ck_events_outscope_importance'),
    sa.CheckConstraint('version >= 1', name='ck_events_version'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_publication_status'), 'events', ['publication_status'], unique=False)
    op.create_table('feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('declared_language', sa.String(length=35), nullable=True),
    sa.Column('default_category', sa.String(length=60), nullable=True),
    sa.Column('trust_score', sa.SmallInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('next_fetch_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consecutive_failures >= 0', name='ck_feeds_failures'),
    sa.CheckConstraint('fetch_interval_minutes BETWEEN 5 AND 1440', name='ck_feeds_interval'),
    sa.CheckConstraint('trust_score IS NULL OR trust_score BETWEEN 0 AND 100', name='ck_feeds_trust'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_feeds_next_fetch_at'), 'feeds', ['next_fetch_at'], unique=False)
    feeds = sa.table('feeds', sa.column('id', sa.UUID()), sa.column('name', sa.Text()), sa.column('url', sa.Text()), sa.column('normalized_url', sa.Text()), sa.column('publisher', sa.Text()), sa.column('declared_language', sa.String()), sa.column('enabled', sa.Boolean()), sa.column('fetch_interval_minutes', sa.Integer()), sa.column('consecutive_failures', sa.Integer()))
    op.bulk_insert(feeds, [{'id': uuid.UUID('2a5c11b1-9ff5-4e0a-bf5f-4ef39a53990b'), 'name': 'Tuoi Tre News — Home', 'url': 'https://news.tuoitre.vn/home.rss', 'normalized_url': 'https://news.tuoitre.vn/home.rss', 'publisher': 'Tuoi Tre News', 'declared_language': 'vi-vn', 'enabled': True, 'fetch_interval_minutes': 30, 'consecutive_failures': 0}])
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('fetch_feed', 'normalize_article', 'analyze_article', 'cluster_event', 'reanalyze_event', 'retention', name='job_type'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'retry_wait', 'succeeded', 'dead', name='job_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0 AND max_attempts BETWEEN 1 AND 100 AND attempts <= max_attempts', name='ck_jobs_attempts'),
    sa.CheckConstraint('priority BETWEEN -1000 AND 1000', name='ck_jobs_priority'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', sa.literal_column('priority DESC'), 'run_after', 'created_at'], unique=False)
    op.create_index('uq_jobs_active_dedupe', 'jobs', ['job_type', 'dedupe_key'], unique=True, postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('queued','running','retry_wait')"))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('source_guid', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('identity_key', sa.String(length=80), nullable=False),
    sa.Column('title_raw', sa.Text(), nullable=False),
    sa.Column('summary_raw', sa.Text(), nullable=True),
    sa.Column('author_raw', sa.Text(), nullable=True),
    sa.Column('title_normalized', sa.Text(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_source', sa.Enum('published', 'updated', 'fetched', name='date_source'), nullable=False),
    sa.Column('detected_language', sa.String(length=35), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_entry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_status', sa.Enum('fetched', 'normalized', 'relevance_ruled', 'ai_analyzed', 'ai_skipped', 'ai_failed', 'event_linked', 'needs_review', 'approved', 'hidden', 'rejected', name='processing_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'identity_key')
    )
    op.create_index(op.f('ix_articles_feed_id'), 'articles', ['feed_id'], unique=False)
    op.create_index(op.f('ix_articles_normalized_url'), 'articles', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_articles_processing_status'), 'articles', ['processing_status'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('before_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('event_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('before_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'version')
    )
    op.create_check_constraint('ck_event_revisions_version', 'event_revisions', 'version >= 1')
    op.create_index(op.f('ix_event_revisions_event_id'), 'event_revisions', ['event_id'], unique=False)
    op.create_foreign_key('fk_events_current_revision', 'events', 'event_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL')
    op.create_table('fetch_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('started', 'succeeded', 'not_modified', 'failed', name='fetch_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('request_etag', sa.Text(), nullable=True),
    sa.Column('request_last_modified', sa.Text(), nullable=True),
    sa.Column('response_etag', sa.Text(), nullable=True),
    sa.Column('response_last_modified', sa.Text(), nullable=True),
    sa.Column('response_body_hash', sa.String(length=64), nullable=True),
    sa.Column('response_body_gzip', sa.LargeBinary(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.CheckConstraint('fetched_count>=0 AND inserted_count>=0 AND updated_count>=0 AND rejected_count>=0', name='ck_fetch_counts'),
    sa.CheckConstraint('http_status IS NULL OR http_status BETWEEN 100 AND 599', name='ck_fetch_http_status'),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_runs_feed_id'), 'fetch_runs', ['feed_id'], unique=False)
    op.create_index(op.f('ix_fetch_runs_job_id'), 'fetch_runs', ['job_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', 'needs_changes', name='review_decision'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('uncertainty_note', sa.Text(), nullable=True),
    sa.Column('ai_proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_event_id'), 'reviews', ['event_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('base_url_identifier', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('rule_version', sa.String(length=80), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('source_article_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('started', 'succeeded', 'failed', 'invalid', name='ai_run_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('external_request_id', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('estimated_cost_usd IS NULL OR estimated_cost_usd >= 0', name='ck_ai_cost'),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='ck_ai_latency'),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name='ck_ai_input_tokens'),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name='ck_ai_output_tokens'),
    sa.CheckConstraint('retry_count >= 0', name='ck_ai_retry'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_article_id'), 'ai_runs', ['article_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_event_id'), 'ai_runs', ['event_id'], unique=False)
    op.create_table('event_articles',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('link_reason', sa.Text(), nullable=False),
    sa.CheckConstraint('similarity_score IS NULL OR similarity_score BETWEEN 0 AND 1', name='ck_event_article_similarity'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'article_id')
    )
    op.create_index('uq_event_primary_source', 'event_articles', ['event_id'], unique=True, postgresql_where=sa.text('is_primary_source'))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_event_primary_source', table_name='event_articles', postgresql_where=sa.text('is_primary_source'))
    op.drop_table('event_articles')
    op.drop_index(op.f('ix_ai_runs_event_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_article_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_reviews_event_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_fetch_runs_job_id'), table_name='fetch_runs')
    op.drop_index(op.f('ix_fetch_runs_feed_id'), table_name='fetch_runs')
    op.drop_table('fetch_runs')
    op.drop_constraint('fk_events_current_revision', 'events', type_='foreignkey')
    op.drop_index(op.f('ix_event_revisions_event_id'), table_name='event_revisions')
    op.drop_table('event_revisions')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_processing_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_normalized_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_feed_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_index('uq_jobs_active_dedupe', table_name='jobs', postgresql_where=sa.text("dedupe_key IS NOT NULL AND status IN ('queued','running','retry_wait')"))
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_feeds_next_fetch_at'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_events_publication_status'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    for enum_name in ('ai_run_status', 'fetch_status', 'review_decision', 'processing_status', 'date_source', 'job_status', 'job_type', 'publication_status', 'event_certainty', 'importance_level', 'relevance_status', 'date_certainty'):
        op.execute(sa.text(f'DROP TYPE {enum_name}'))
    # ### end Alembic commands ###
